# Chemin absolu vers le config.yaml du projet DLC custom utilisé en
# `--mode custom` par run_dlc_inference.py.
dlc_project_config: E:\DLC\souris-bottomview-Leo-2026-06-05\config.yaml


default_arenes_coords:
  A1:
  - 599
  - 40
  - 495
  - 465
  A2:
  - 599
  - 506
  - 496
  - 503
  A3:
  - 106
  - 501
  - 490
  - 505
  A4:
  - 110
  - 39
  - 486
  - 460
